name: Node.js - CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run eslint:check

      # - name: Prettify code
      #   run: npm run prettier:check --config .prettierrc.json

      - name: Build application
        run: npm run build

      - name: Test application
        run: npm run test

      # - name: Code coverage report
      #   run: npm run test:coverage

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Install Netlify CLI
        run: npm install --save-dev netlify-cli

      - name: Deploy
        run: |
          netlify build
          netlify deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
