name: Production Build

on:
  workflow_call:
    inputs:
      runs-on:
        description: The type of machine to run the job on.
        type: string
        default: ubuntu-latest
      node-version:
        description: The version of Node.js to be used.
        type: string
        default: 18.x

jobs:
  build:
    name: Node.js (${{ inputs.node-version }})

    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
