name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Linters
    uses: ./.github/workflows/lint.yml
  build:
    name: Production build
    needs: lint
    uses: ./.github/workflows/production-build.yml
