name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  # code-quality:
  #   name: Code quality
  #   uses: ./.github/workflows/code-quality.yml
  build:
    name: Production build
    # needs: code-quality
    uses: ./.github/workflows/production-build.yml
