name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Production build
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    uses: ./.github/workflows/production-build.yml
    with:
      node-version: ${{ matrix.node-version }}

