name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Production build
    uses: ./.github/workflows/production-build.yml
  test:
    name: Unit Tests
    needs: build
    uses: ./.github/workflows/unit-tests.yml

