name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Code Linting
    uses: ./.github/workflows/code-linting.yml
  build:
    name: Production build
    needs: lint
    uses: ./.github/workflows/production-build.yml
